var num1 = 40;
var num2 = -100;
var num3 = 3.33;
var num4 = 3;
var str1 = "12345";
var str2 = "yo mama so fat";
var str3 = 'javascriptstr';
var boo1 = true;
var boo2 = false;
var und = x;
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(str1);
console.log(str2);
console.log(str3);
console.log(boo1);
console.log(boo2);
console.log(und);